CREATE TABLE TB_ERP_RECEPTION (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    operation_date TIMESTAMP NOT NULL,
    operation_by VARCHAR(30) NOT NULL,
    reception_identifier VARCHAR(9) NOT NULL,
    purchase_order VARCHAR(9) NOT NULL,
    pallet_id VARCHAR(13) NOT NULL,
    sn VARCHAR(255) NOT NULL,
    cpe_instance_id BIGINT NOT NULL,

    CONSTRAINT fk_cpe_reception
        FOREIGN KEY (cpe_instance_id)
        REFERENCES TB_CPE_INSTANCE(id)
);