CREATE TABLE TB_ERP_TESTING (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    operation_date TIMESTAMP NOT NULL,
    operation_by VARCHAR(30) NOT NULL,
    mac VARCHAR(255) NOT NULL,
    start_test TIMESTAMP,
    end_test TIMESTAMP,
    status VARCHAR(50),
    cpe_instance_id BIGINT,
    CONSTRAINT fk_testing_cpe
        FOREIGN KEY (cpe_instance_id)
        REFERENCES TB_CPE_INSTANCE(id)
);