CREATE TABLE TB_TESTING (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    mac VARCHAR(255) NOT NULL,
    tested_by VARCHAR(255) NOT NULL,
    cpe_instance_id BIGINT NOT NULL,
    start_test VARCHAR(16),
    end_test VARCHAR(16),
    status VARCHAR(50),

    CONSTRAINT fk_cpe_instance_testing
        FOREIGN KEY (cpe_instance_id)
        REFERENCES TB_CPE_INSTANCE(id)
        ON DELETE CASCADE
);