CREATE TABLE TB_ERP_OPERATION_HISTORY (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        reception_id BIGINT NOT NULL,
        testing_id BIGINT NOT NULL,

        CONSTRAINT fk_operation_history_reception
            FOREIGN KEY (reception_id)
            REFERENCES TB_ERP_RECEPTION(id),

        CONSTRAINT fk_operation_history_testing
            FOREIGN KEY (testing_id)
            REFERENCES TB_ERP_TESTING(id)
);