spring:
  #Configuração base de dados em memória H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:refurb-employees-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

#Add logging to application
logging:
  level:
    root: INFO #Define o nível de log geral da aplicação
    org.hibernate.SQL: DEBUG #Log para o Hibernate quando constrói as queries
    org.hibernate.type.descriptor.sql: TRACE #Log Binding Parâmetros SQL
    org.springframework.data.jpa.repository: DEBUG #Log chamadas aos métodos nos repositories
    org.springframework.context.annotation: DEBUG