CREATE TABLE TB_INTERNAL_EMPLOYEE (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    worker_no VARCHAR(5) UNIQUE,
    employee_type VARCHAR(50) NOT NULL,

    FOREIGN KEY (id) REFERENCES TB_EMPLOYEE(id)
);
